site_name: Previsão das medias
repo_url: https://github.com/matkiap/mateus-media
repo_name: matkiap/mateus-media
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheet/extra.css